# Generated by Django 5.1.3 on 2025-05-27 15:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezvousInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendezvous', models.DateTimeField(default=django.utils.timezone.now)),
                ('termine', models.BooleanField(default=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modification_count', models.PositiveIntegerField(default=0)),
                ('inspection_complete', models.BooleanField(default=False)),
                ('date_proposee', models.DateTimeField(blank=True, null=True)),
                ('statut_proposition', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('raison_proposition', models.TextField(blank=True, null=True, verbose_name='Raison du changement de date')),
                ('agent_recouvrement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.demandecredit')),
            ],
        ),
    ]
