# Generated by Django 5.1.3 on 2025-05-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0002_rendezvousinspection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InspectionRendezvous',
        ),
    ]
